spring.application.name=identity-service
server.port=${SPRING_SERVER_PORT}
server.servlet.context-path=/api/v1/identity

#config hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.connection.release_mode=after_transaction
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#jwt key
jwt.secret_key=${SPRING_JWT_SECRET_KEY}
jwt.access_token_expires=${SPRING_JWT_ACCESS_TOKEN_EXPIRES}
jwt.refresh_token_expires=${SPRING_JWT_REFRESH_TOKEN_EXPIRES}

spring.servlet.multipart.max-file-size=${SPRING_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_REQUEST_SIZE}

#redis connection
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

#config eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_DEFAULT_ZONE}

#firebase config
firebase.bucket-name=${FIREBASE_BUCKET_NAME}
firebase.image-url=${FIREBASE_IMAGE_URL}

#kafka config
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#AI config
recommendation.url=${RECOMMENDATION_URL}