spring.application.name=api-gateway
logging.level.root= INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator= INFO
logging.level.org.springframework.cloud.gateway= TRACE

server.port=${SPRING_SERVER_PORT}
app.api-prefix=/api/v1

#identity route
spring.cloud.gateway.routes[0].id=identity-service
spring.cloud.gateway.routes[0].uri=lb://identity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=${app.api-prefix}/identity/**

#discovery route
spring.cloud.gateway.routes[1].id=discovery-server
spring.cloud.gateway.routes[1].uri=http://localhost:8761
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[1].filters[0]=SetPath=/

#discovery server static resource file
spring.cloud.gateway.routes[2].id=discovery-server-static
spring.cloud.gateway.routes[2].uri=http://localhost:8761
spring.cloud.gateway.routes[2].predicates[0]=Path=/eureka/**

#document service
spring.cloud.gateway.routes[3].id=document-service
spring.cloud.gateway.routes[3].uri=lb://document-service
spring.cloud.gateway.routes[3].predicates[0]=Path=${app.api-prefix}/document/**

#notification service
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=${app.api-prefix}/notification/**

#websocket server
spring.cloud.gateway.routes[5].id=websocket-server
spring.cloud.gateway.routes[5].uri=lb://websocket-server
spring.cloud.gateway.routes[5].predicates[0]=Path=/ws/**
spring.cloud.gateway.routes[5].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
spring.cloud.gateway.routes[5].filters[1]=RemoveRequestHeader=Sec-WebSocket-Ke

#study group service
spring.cloud.gateway.routes[6].id=study-group-service
spring.cloud.gateway.routes[6].uri=lb://study-group-service
spring.cloud.gateway.routes[6].predicates[0]=Path=${app.api-prefix}/study-group/**


#config eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_DEFAULT_ZONE}

#redis connection
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}