spring.application.name=discovery-server
server.port=${SPRING_SERVER_PORT}

#eureka config
eureka.instance.hostname=${EUREKA_HOST_NAME}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.default-zone=${EUREKA_DEFAULT_ZONE}