spring.application.name=study-group-service
server.port=${SPRING_SERVER_PORT}
server.servlet.context-path=/api/v1/study-group

#config hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.connection.release_mode=after_transaction
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#config eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_DEFAULT_ZONE}

#redis connection
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}

#UTC TIME
spring.utc.time=${UTC_TIME}

#circuit breaker config
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=60
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

#Resilience4j Properties of identity service
resilience4j.circuitbreaker.instances.document-service.base-config=default
resilience4j.circuitbreaker.instances.document-service.waitDurationInOpenState=5s

#Resilience4j Properties of chatbot service
resilience4j.circuitbreaker.instances.identity-service.base-config=default
resilience4j.circuitbreaker.instances.identity-service.waitDurationInOpenState=5s

#Resilience4J Timeout Properties
resilience4j.timelimiter.instances.default.timeout-duration=10s

#Resilience4J Retry Properties
resilience4j.retry.instances.default.max-attempts=3
resilience4j.retry.instances.default.wait-duration=5s