spring.application.name=e-learning-service
server.port=${SPRING_SERVER_PORT}
server.servlet.context-path=/api/v1/e-learning

#config eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE}

#config hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.connection.release_mode=after_transaction
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#redis connection
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}

#chatbot config
app.ai-service.url=${CHATBOT_URL}

#circuit breaker config
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.document-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.document-service.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.document-service.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.document-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.document-service.failureRateThreshold=60
resilience4j.circuitbreaker.instances.document-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.document-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.document-service.waitDurationInOpenState=5s

#Resilience4J Timeout Properties
resilience4j.timelimiter.instances.document-service.timeout-duration=10s

#Resilience4J Retry Properties
resilience4j.retry.instances.document-service.max-attempts=3
resilience4j.retry.instances.document-service.wait-duration=5s
