spring.application.name=batch-service
server.port=8084

#config database source
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.connection.release_mode=after_transaction
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

#config eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_DEFAULT_ZONE}
